apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-web
  labels:
    app: chatgpt-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chatgpt-web
    spec:
      containers:
        - name: chatgpt-web
          image: chenzhaoyu94/chatgpt-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: OPENAI_API_KEY
              value: "${OPENAI_API_KEY}"
            - name: OPENAI_API_BASE_URL
              value: "${OPENAI_API_BASE_URL}"
            - name: OPENAI_API_MODEL
              value: "${OPENAI_API_MODEL}"
            - name: AUTH_SECRET_KEY
              value: "${AUTH_SECRET_KEY}"
            - name: HTTPS_PROXY
              value: "${HTTPS_PROXY}"
            - name: ALL_PROXY
              value: "${ALL_PROXY}"
            - name: SOCKS_PROXY_HOST
              value: "${SOCKS_PROXY_HOST}"
            - name: SOCKS_PROXY_PORT
              value: "${SOCKS_PROXY_PORT}"
            - name: SOCKS_PROXY_USERNAME
              value: "${SOCKS_PROXY_USERNAME}"
            - name: SOCKS_PROXY_PASSWORD
              value: "${SOCKS_PROXY_PASSWORD}"
            - name: TIMEOUT_MS
              value: "${TIMEOUT_MS}"
            - name: OPENAI_API_DISABLE_DEBUG
              value: "${OPENAI_API_DISABLE_DEBUG}"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatgpt-web
  name: chatgpt-web
spec:
  ports:
    - name: chatgpt-web
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: chatgpt-web
  type: ClusterIP
